[RFR] Launch a new game
marmelab/quixo-isomorphic pull request #1
Opened 2019-06-26 13:10 UTC by HALLERPierre

[trello](https://trello.com/c/J0Q0i62A/1-1-as-fred-i-want-to-launch-a-new-game)

# TODO

- [ ] Create app
- [ ] Create landing page
- [ ] Create game page
- [ ] Add styles
- [ ] Add statics files
- [ ] Add docker-compose file
- [ ] Add Makefile

# Result
![empty-board](https://user-images.githubusercontent.com/6030943/60182414-90f91b80-9824-11e9-9856-8cd2f623c759.gif)

2019-06-26 13:14 UTC, HALLERPierre commented on src/pages/_document.js
> +import Document from "next/document";
The `src/pages/_document.js` file is necessary to inject styles in the page for `styled-components`. Found this solution in Next.js doc.

2019-06-26 13:33 UTC, zyhou requested changes
Missing :

- make stop
- readme update
- licence update 
- linting

travis not working ?

2019-06-26 13:33 UTC, zyhou commented on src/package.json
> +    "babel-plugin-styled-components": "1.10.2",
Babel plugin is dev dep

2019-06-26 13:33 UTC, zyhou commented on src/pages/game.js
> +  <div>
div is needed ?

2019-06-26 14:46 UTC, Kmaschta commented
Also, can you install some linter rules and enforce them?
Would be awesome to have the prettier rules from eslint, this is the one I'm used to.

2019-06-27 10:09 UTC, zyhou approved these changes

2019-06-27 11:52 UTC, Kmaschta approved these changes

2019-06-27 11:52 UTC, merged